package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	if err := os.MkdirAll("internal/gen/throne/v1", 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll("api/openapi", 0o755); err != nil {
		return err
	}
	generated := `// Code generated by scripts/genproto; DO NOT EDIT.
package thronev1

type User struct { ID string; Email string }
type Device struct { ID string; UserID string; CertificateThumbprint string }
type Capture struct { ID string; UserID string; DeviceID string; S3Key string; ContentHash string; SizeBytes int64; Status string }
type Finding struct { ID string; CaptureID string; UserID string; Result string; Confidence float64; Reason string }
type CaptureAck struct { CaptureID string; S3Key string; ContentHash string }
type InferRequest struct { CaptureID string; S3Key string; ModelVersion string; ContentHash string }
type InferResponse struct { Finding *Finding; Confidence float64 }
`
	formatted, err := format.Source([]byte(generated))
	if err != nil {
		return err
	}
	if err := os.WriteFile("internal/gen/throne/v1/generated.go", formatted, 0o644); err != nil {
		return err
	}
	openapi := map[string]any{"swagger": "2.0", "info": map[string]any{"title": "Throne API", "version": "v1"}, "paths": map[string]any{"/v1/users/{user_id}/captures": map[string]any{"get": map[string]any{"summary": "List captures"}}, "/v1/captures/{capture_id}": map[string]any{"get": map[string]any{"summary": "Get capture"}}, "/v1/findings/{finding_id}": map[string]any{"get": map[string]any{"summary": "Get finding"}}, "/v1/captures/{capture_id}/image-url": map[string]any{"post": map[string]any{"summary": "Create signed image URL"}}}}
	b, err := json.MarshalIndent(openapi, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join("api/openapi", "throne.v1.swagger.json"), append(b, '\n'), 0o644); err != nil {
		return err
	}
	fmt.Println("generated internal/gen/throne/v1/generated.go and api/openapi/throne.v1.swagger.json")
	return nil
}
